## Objective: Cache the inverse of a matrix
## Use: Inversion is a costly computation and caching will lead to efficiency
## makeCacheMatrix: Matrix object capable of caching its inverse. Essentially is a 
##list with various functions for handling the caching the inverse of a matrix.
## cacheSolve: Computes the inverse or returns the cached inverse 
## of a matrix for a matrix generated by makeCacheMatrix.


## makeCacheMatrix returns a list of functions that helps in:
## 1. Set the value of the matrix
## 2. Get the value of the matrix
## 3. Cache the inverse of a matrix
## 4. Get the cached inverse of a matrix

makeCacheMatrix<-function(x=matrix()){
        inv<-NULL
        set<-function(y){
                x<<-y
                inv<<-NULL
        }
        get<-function() {
                x
        }        
        setinverse<-function(inverse) {
                inv<<-inverse
        }
        getinverse<-function() {
                inv
        }
        list(set=set,get=get,setinverse=setinverse,getinverse=getinverse)
}


## cacheSolve returns the inverse of a matrix created by makeCacheMatrix 
##passed to it. It will either compute the inverse OR return a cached value
## of the inverse stored in makeCacheMatrix

cacheSolve<-function(x,...){

        inv<-x$getinverse()
        if(!is.null(inv)){
                message("getting cached data")
                return(inv)
        }
        message("no cached data! calculating inverse")
        data<-x$get()
        inv<-solve(data)
        x$setinverse(inv)
        inv
}
        

